name: Google Sheets Update

on:
  push:
    branches:
      - main

jobs:
  update-sheet:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run script
      env:
        GCP_KEY_JSON: ${{ secrets.GCP_KEY_JSON }}
      run: |
        echo "$GCP_KEY_JSON" > key.json
        python QR-V4-last.py
